name: CI/CD Deploy

on:
  push:
    branches:
      - main  # disparar deploy só na branch main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      BASE_URL: ${{ secrets.BASE_URL }}
      ALGORITHM: ${{ secrets.ALGORITHM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check docker and compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/metrics; then
              echo "API is up"
              exit 0
            fi
            echo "Waiting for API..."
            sleep 5
          done
          echo "API did not become ready in time"
          exit 1

      - name: Run tests
        run: |
          pytest -v
        continue-on-error: true

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STOCK_SERVER_IP }}
          username: ${{ secrets.STOCK_SERVER_USER }}
          key: ${{ secrets.STOCK_SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/store_and_stock_service
            git pull origin main
            sudo docker compose up -d --build
