name: CI/CD Deploy

on:
  push:
    branches:
      - main  # dispara deploy só na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.STOCK_SERVER_IP }}
        username: ${{ secrets.STOCK_SERVER_USER }}
        key: ${{ secrets.STOCK_SERVER_SSH_KEY }}
        port: 22
        script: |
          cd
          cd store_and_stock_service
          git pull origin main
          sudo docker-compose up -d --build

